= pge-tod

Compare time-of-day cost versus basic rate for Portland General Electric's Time
of Day program.

== Usage

* Download usage data from portlandgeneral.com in CSV format.
* Run ./pge-tod nameoffile.csv


== Example output

....
processing 2023-11-08_to_2023-12-10.csv
    namespace(starttime=datetime.datetime(2023, 11, 8, 0, 0), usage_kwh=0.44, tod_category='off', tod_rate=7.43, tod_cost_cents=3.27, basic_cost_cents=8.56)
    namespace(starttime=datetime.datetime(2023, 11, 8, 0, 15), usage_kwh=0.44, tod_category='off', tod_rate=7.43, tod_cost_cents=3.27, basic_cost_cents=8.56)
    [...]
    namespace(starttime=datetime.datetime(2023, 12, 10, 23, 30), usage_kwh=0.31, tod_category='off', tod_rate=7.43, tod_cost_cents=2.3, basic_cost_cents=6.03)
    namespace(starttime=datetime.datetime(2023, 12, 10, 23, 45), usage_kwh=0.31, tod_category='off', tod_rate=7.43, tod_cost_cents=2.3, basic_cost_cents=6.03)
namespace(earliest=datetime.datetime(2023, 11, 8, 0, 0), latest=datetime.datetime(2023, 12, 10, 23, 45), readings=3168, tod_cost_usd=242.42, basic_cost_usd=404.03)
....
